### ISSUE TITLE
[SUGGESTION] More component features

### ISSUE THREAD

**Issue by UsainSrht** [ShaneBeee/SkBee#158]
**Is your feature request related to a problem? Please describe.**
Full support of components :)

- font of component
- send component action bar effect
- send component title effect
- be able to send normal strings in send component effect

**Describe the solution you'd like**
`set font of {_c} to font("uniform")` font(string) function or just string
`send component action bar {_c::*} to (all players)` #from player if possible
`send component title {_c::1} with subtitle {_c::2} for (5 seconds) with fade in (0.1 seconds) and fade out (0.1 seconds) to (all players)` #from player if possible
`send component ({_c::*}, " -*- ", {_cd::4}) to (all players) from player`

**Describe alternatives you've considered**

**Additional context**

**Comment by UsainSrht** [comment]
Also usability of the components with effect commands came to my mind. Just like items.
ex: `!send component (((component from "hello") with font "uniform") with color red)`

**Comment by ShaneBeee** [comment]
Ok so far I have added the action bar component, ability to send strings as well, and the get/set for font.

> send component title effect

Spigot/Bungee API doesn't have anything for this unfortunately. While Paper DOES have this, their system is totally different, and not something I want to dive into anytime soon. 
Maybe in the future.



> Also usability of the components with effect commands came to my mind. Just like items.
> ex: `!send component (((component from "hello") with font "uniform") with color red)`

I do not want to do this, as people will abuse the crap out of this, and end up bitching/complaining that they're having long parse times due to insanely long lines of code.

**Comment by ShaneBeee** [comment]
Im just re-opening this
I like to keep them until I've released. Just so I know all what I've done prior to release.
