### ISSUE TITLE
[BUG] SkBee makes the Location function take longer to parse

### ISSUE THREAD

**Issue by MinecraftMan1013number2** [ShaneBeee/SkBee#159]
**Describe the bug**
When SkBee is on my server, it makes the vanilla Skript Location function take much longer to parse. It only happens with certain code

**To Reproduce**
I used this code to make it lag. The `{TestLoc}` variable does not have to be set.
```vbs
function TestLoc():
	set {_previousLoc} to {TestLoc}
	
	set {_x} to x coord of {_previousLoc}
	set {_y} to y coord of {_previousLoc}
	set {_z} to z coord of {_previousLoc}

	set {_newLoc} to location({_x}, {_y}, {_z}, world of {_previousLoc}, yaw of {_previousLoc}, pitch of {_previousLoc})
	set {TestLoc} to {_newLoc}
```

but this code had a normal reload time.
```vbs
function TestLoc():
	set {_newLoc} to location(0, 0, 0, world "world", 0, 0)
```

**Expected behavior**
It loads in normal time

**Screenshots/Errors**
If applicable, add screenshots/errors to help explain your problem.
Code with skBee:
![image](https://user-images.githubusercontent.com/70504198/163862913-2a2750d7-028b-4fc1-a9b9-50c8cd6028a5.png)

Same code without skBee:
![image](https://user-images.githubusercontent.com/70504198/163863383-c8d2878b-f057-4969-b190-6e6c1d61428e.png)

**Version Info:**
 - **SkBee Version:** 1.15.2
-  **Skript Version:** 2.6.1
 - **Server Version/Platform** Paper 1.18.2

**Additional context**

**Comment by ShaneBeee** [comment]
I did some testing:

Using your test code:
```vb
function TestLoc():
	set {_previousLoc} to {TestLoc}
	
	set {_x} to x coord of {_previousLoc}
	set {_y} to y coord of {_previousLoc}
	set {_z} to z coord of {_previousLoc}

	set {_newLoc} to location({_x}, {_y}, {_z}, world of {_previousLoc}, yaw of {_previousLoc}, pitch of {_previousLoc})
	set {TestLoc} to {_newLoc}
```

Outcome without SkBee:
```
> sk reload test
[13:47:25 INFO]: [Skript] Reloading test.sk...
[13:47:27 INFO]: [Skript] Successfully reloaded test.sk. (1567ms)
```

Changing your test code a smidge, I removed all the expressions from within the function (since that in itself causes parsing times to be longer), and used local vars instead
```vb
function TestLoc():
	set {_previousLoc} to {TestLoc}
	
	set {_x} to x coord of {_previousLoc}
	set {_y} to y coord of {_previousLoc}
	set {_z} to z coord of {_previousLoc}


	set {_w} to world of {_previousLoc}
	set {_yaw} to yaw of {_previousLoc}
	set {_pitch} to pitch of {_previousLoc}

	set {_newLoc} to location({_x}, {_y}, {_z}, {_w}, {_yaw}, {_pitch})
	set {TestLoc} to {_newLoc}
```
outcome without SkBee:
```
> sk reload test
[13:49:12 INFO]: [Skript] Reloading test.sk...
[13:49:12 INFO]: [Skript] Successfully reloaded test.sk. (37ms)
```

With your code, 1567ms to parse, with removing the expressions from within the function 37ms to parse.
As you can see writing code the way you did even without SkBee is going to create some longer parsing times.

Why SkBee is making it even longer, that I'm not sure, there is probably a conflicting issue

Testing with SkBee, same code
1)
```
> sk reload test
[13:51:35 INFO]: [Skript] Reloading test.sk...
[13:52:12 INFO]: [Skript] Successfully reloaded test.sk. (22389ms)
```

2)
```
> sk reload test
[13:51:35 INFO]: [Skript] Reloading test.sk...
[13:51:35 INFO]: [Skript] Successfully reloaded test.sk. (75ms)
```

As you can see, your code with SkBee ran at 22,389ms, where as my code with SkBee ran at 75ms (a smidge longer with SkBee but not a really noticeable difference)

That said, its probably something SkBee has added (with world stuff) that is conflicting, and unfortunately there's really nothing I can do to fix this issue. 
Write your code to not use expressions within functions and you should be good to go.
