### ISSUE TITLE
[SUGGESTION] Matocolotoe / Skript-1.8

### ISSUE THREAD

**Issue by 1hmd** [ShaneBeee/SkBee#169]
I would like to see your addon work with Matocolotoe / Skript-1.8 in the future ;)

**Comment by ShaneBeee** [comment]
This won't happen.
Its not that SkBee doesn't work with that fork of Script, its that SkBee doesn't support outdated versions of Minecraft.
We are currently in Minecraft 1.18.2, with 1.19 coming out sometime this year. 1.8 is 10 versions behind at this point.
While I understand many users still use 1.8.x, SkBee won't be supporting it. This is mainly due to some NMS (backend Minecraft code) usage, as well as updated/changed Bukkit API usage. 

SkBee will only be supporting the latest 3 versions of Minecraft.
