### ISSUE TITLE
[BUG] Scoreboards disappearing upon rejoining

### ISSUE THREAD

**Issue by Gavins38** [ShaneBeee/SkBee#193]
**Describe the bug**
Scoreboards dont appear when rejoining the server

**To Reproduce**
```vb
on join:
	while player is online:
		wait 1 second
		set title of player's scoreboard to "AmethystRPG"
		set line 1 of player's scoreboard to "Look mah I'm on Minecraft"
		set line 15 of player's scoreboard to "uhhhhhhhhh"

command /toggleon:
	trigger:
		toggle player's scoreboard on

command /toggleoff:
	trigger:
		toggle player's scoreboard off
```

Rejoin the server and the scoreboard will disappear 

**Expected behavior**
To show the scoreboard..

**Screenshots/Errors**
![image](https://user-images.githubusercontent.com/67829574/174838773-8b5c8bc0-0120-4062-aa26-322a10fd81e7.png)

**Version Info:**
 - **SkBee Version:** 1.16.1
-  **Skript Version:** Skript 2.6.2-nightly-b89d420
 - **Server Version/Platform** Paper 1.19

**Additional context**

**Comment by ShaneBeee** [comment]
using my own code, I had no issues, but using your code I was having issues like you described.

Im not sure why, but if I move the `wait 1 second` to AFTER the code, it works, ex:
```vb
on join:
	while player is online:
		set title of player's scoreboard to "AmethystRPG"
		set line 1 of player's scoreboard to "Look mah I'm on Minecraft"
		set line 15 of player's scoreboard to "uhhhhhhhhh"
		wait 1 second	
```
Im not sure why but this works. Try this, because its standard practice that you add the wait as the last part of your while loop. 

Also a tidbit, I recommend putting the title part BEFORE the while loop, since you generally only need to set the title once. 
ex:
```vb
on join:
	set title of player's scoreboard to "AmethystRPG"
	while player is online:
		set line 1 of player's scoreboard to "Look mah I'm on Minecraft"
		set line 15 of player's scoreboard to "uhhhhhhhhh"
		wait 1 second
```
You should only put in the while loop, the things that actually need to update every X time. 

That said, Im going to leave this issue open, because I want to try figure out why this is happening.

**Comment by ShaneBeee** [comment]
Ok so I figured out the issue, here is what happens:

(in SkBee)
When a player quits, their scoreboard is deleted.

(in your script)
you have this:
```vb
	while player is online:
		wait 1 second
		set title of player's scoreboard to "AmethystRPG"
		set line 1 of player's scoreboard to "Look mah I'm on Minecraft"
		set line 15 of player's scoreboard to "uhhhhhhhhh"
```
so basically what is happening here, is if the player quits within that 1 second, their scoreboard is delete, but the rest of your loop will continue, so if you set the title of the scoreboard (while the player is offline), a new scoreboard is created.
When they player logs in, it grabs that new scoreboard (which is an invalid scoreboard)

Luckily this is an easy fix.
