### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by samirmedani** [ShaneBeee/SkBee#227]
**Describe the bug**
Hello,
No matter what script I code SKbee gives me an error that unloads all my scripts.
It is very problematic because SKbee is very useful to me especially concerning the NBT, I could not do without it.
The problem being that even if the script I coded does not use expressions from SKbee the error appears.

**To Reproduce**
Start or restart the server after putting the script(s).

**Expected behavior**
That no errors occur and that my scripts load.

**Screenshots/Errors**
![image](https://user-images.githubusercontent.com/40952685/181670051-6220eeaf-a536-4ec6-a40e-7bf02b1a5965.png)

**Version Info:**
 ![image](https://user-images.githubusercontent.com/40952685/181670130-002485a1-6864-4a18-9fb2-b80a0796c724.png)

**Additional context**
I did not find any other context.

Ty for help !

**Comment by ShaneBeee** [comment]
outdated SkBee version.
When reporting issues, please make sure to test on latest version.

**Comment by samirmedani** [comment]
Sorry, I thought I had the latest version.
I updated and here is the error now.

![image](https://user-images.githubusercontent.com/40952685/181736202-890f7c0b-05ff-4a33-8bc3-815f4354b106.png)

**Comment by ShaneBeee** [comment]
So from what I can see, in your previous imagine, you had an error regarding Skript discarding variables due to some missing database situation.

That said, the error is caused when trying to load an NBT variable from the variable file. 
My guess is your variable file is corrupt or something. 
While the error IS coming from SkBee, its actually an issue with your variables file.

I can sort of change how the error goes, but other than that, I can't fully fix this as its not technically a bug.

I will mark it as a bug, just because I need to handle the error a little differently.

**Comment by samirmedani** [comment]
Thank you for your answer.
From my side what can I do to solve the problem? I can maybe try to clear all the variables that I no longer use in the variables file?

**Comment by ShaneBeee** [comment]
Due to the fact that your variable file may be corrupt I'm not really sure what you could do here.
Personally I could not replicate this issue.

**Comment by samirmedani** [comment]
I deleted the excel variables.csv file and and I no longer have the error.

Subsequently I redefined my variables containing NBTs and I had no error.

I optimize and verify each script by doing server reloads to eliminate errors.

**Comment by ShaneBeee** [comment]
Im going to be doing some changes in SkBee 1.18.x with NBT, due to another error I found when stopping the server. 
Hopefully this will prevent any future NBT/Variable issues

**Comment by ShaneBeee** [comment]
Fixed in SkBee 1.18.0-Beta3
