### ISSUE TITLE
[SUGGESTION] Indicate the plugins to use

### ISSUE THREAD

**Issue by DKSM** [ShaneBeee/SkBee#233]
Hello,

I tried to use bossbars to no avail and found in the console logs that _"To use SkBee BossBars, please remove the addon which has registered BossBars already."_

This is a big problem because these are not small addons that add this functionality and it is not possible to disable them.

Could we not have a syntax which indicates that it is SKBEE which must be used as certain addons do?

Example:
set {_bar} to boss bar named "test"
>
set {_bar} to skbee boss bar named "test"

**Comment by ShaneBeee** [comment]
In the case of boss bars that's not possible.
The reason is because to use boss bars the addon needs to register class infos for some classes (Skript calls these "types"), and since both addons have to register the same one, that would cause an error.
SkBee is preventing this error, by skipping all the boss bar stuff.
I recommend just using the other addon for their boss bars

**Comment by DKSM** [comment]
Thanks for the fast reply
