### ISSUE TITLE
[SUGGESTION] with nbt

### ISSUE THREAD

**Issue by gagore** [ShaneBeee/SkBee#238]
**Is your feature request related to a problem? Please describe.**
I hope to use ``with nbt`` very much

**Describe the solution you'd like**

change ``enchanted book named "&6hello" with lore "&7world" with nbt "{HideFlags:63}"`` to

``enchanted book named "&6hello" with lore "&7world" with nbt compound of "{HideFlags:63}"``
or
``enchanted book named "&6hello" with lore "&7world" with nbt item compound of "{HideFlags:63}"``

Error when executing the following syntax
If it was a bug, please refer to it

```
"{HideFlags:63}" is neither an item stack, an item type nor an entity type
```
```
enchanted book named "&6hello" can't have anything added to it
```

**Comment by ShaneBeee** [comment]
your second option:
`enchanted book named "&6hello" with lore "&7world" with nbt compound of "{HideFlags:63}"`

Is already correct syntax. I did notice for some reason sometimes it doesn't work, but if you use `from` instead of `of` it works
ex:
`enchanted book named "&6hello" with lore "&7world" with nbt compound from "{HideFlags:63}"`

This isn't an issue with SkBee, I believe this is a weird quirk with Skript.
