### ISSUE TITLE
[SUGGESTION] accurate block data of rotated structure

### ISSUE THREAD

**Issue by boxic** [ShaneBeee/SkBee#260]
**Is your feature request related to a problem? Please describe.**
I was hoping that getting the block data of a blockstate after rotating a structure would give me the block data AFTER rotations were applied (useful for custom block placing) but it shows the data from before the rotation was applied

**Describe the solution you'd like**
block data of [blockstate of a rotated schematic] would return the blockstate AFTER the rotation was done
Doing the same for the offset would be awesome too! But that's much easier to do manually than working with a string of block data tags on the end of the block id 0_o

**Describe alternatives you've considered**
I've tried working with the block data myself, but it's a string, and that basically means that my simplest option is to use the normal schematic pasting, then loop over all the blocks, then do any block data manipulation I need

**Additional context**
If nothing else, please make the schematic block data compatible with skript's vanilla block data, allowing us to do things like `set {_data::*} to block data tags of  {_blockdata}` or `set block data tag "waterlogged" of {_blockdata} to true`
Currently, it seems to just be a string, and that makes me sadface

**Comment by ShaneBeee** [comment]
Ok a couple things here:

The Bug:
So the issue here is something I don't think I can fix. SkBee's structure object is a custom object in SkBee (called... StructureBee), this was created to help manipulate the Bukkit Structure object.
The Bukkit Structure object itself isn't manipulated (ie: rotation, mirror, etc), that stuff happens only on place. 
Because Bukkit doesn't have anything for that stuff, I decided to create a custom object, where you could manipulate said structure object (ie: rotation, mirror, etc), and then when you place it in the world all that stuff would apply. 
Because of that, the block states come from the Bukkit object, and since that object is never changed, the block states will be the original states. 
That said, the only solution would be for me to loop thru every block state and try to manipulate each one. Since Minecraft has a bunch of super weird states for blocks, that just wouldn't really be tangible. 
I unfortunately have to say, this won't be something I can fix.

The Suggestion:
> If nothing else, please make the schematic block data compatible with skript's vanilla block data,

it already is:
<https://skripthub.net/docs/?id=6311>
This expression will return the Skript "block data" of a structure block state

**Comment by boxic** [comment]
> it already is:
> https://skripthub.net/docs/?id=6311
> This expression will return the Skript "block data" of a structure block state
`set {_data::*} to block data tags of {_blockdata}`
and
`set block data tag "waterlogged" of {_blockdata} to true`
don't work, which is what led me to believe that it doesn't behave like a normal block data tag - perhaps I'm misunderstanding, and a block data tag has to refer to an actual block that exists or something to be manipulated like that?

Either way, a way to get a list of the blockdata keys and values would be awesome, that way you could easily do your own loops to swap values around when you do a custom structure paste, by using the two code snippets above

Thoughts?

**Comment by ShaneBeee** [comment]
I'll have to do some re-works to that expression.

The block data tag expression is for blocks, not block data/states

**Comment by ShaneBeee** [comment]
after looking thru the Bukkit API, I have come to see that the state of the blocks in structures can't be changed, as seen here:

[List](https://docs.oracle.com/javase/8/docs/api/java/util/List.html)<[BlockState](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/block/BlockState.html)> [getBlocks](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/structure/Palette.html#getBlocks())() Gets a copy of the blocks this Palette is made of.

It returns a COPY of the blockstates, which means they can't be modified
