### ISSUE TITLE
[BUG] Structures dont work anymore

### ISSUE THREAD

**Issue by Lemekia** [ShaneBeee/SkBee#262]
Well i just updated to 1.19.2 and the structure system wont work. On 1.18 it worked fine.

```
command /test:
    trigger:
        if structure "test" exists:
            set {_s} to structure named "test"
            place structure {_s} at location of player
            send "Spawning..."
        else:
            send "Nope"
```
It dosent find the structures, it says nope. The structures are saved in (SERVER)/world/generated/minecraft/structures

- Skript Ver.: 2.6.3
- SkBee Ver.: 2.3.1

**Comment by ShaneBeee** [comment]
This is a "my bad" kind of situation.

I did a rework to how SkBee fetches namespaces to use a util method rather than repeating my code everything.
That said, if no namespace is provided, it will default to "skbee"

Prior to this change all structures were saved in the Minecraft folder, and now they're in an SkBee folder.

All you need to do is use "minecraft:test" and you should be good to go

**Comment by Lemekia** [comment]
Thats for the quick help!
