### ISSUE TITLE
Multiple color codes

### ISSUE THREAD

**Issue by Ofus-Will** [ShaneBeee/SkBee#3]
Warning: this is on minehut so odds are it's probably on their end

I believe there is a bug with skbee (skboard's features), it would appear it does not support multiple colour codes

```
on join:
    set title of player's scoreboard to "&6&lServer Info"
    while player is online:
        set line 1 of player's scoreboard to "&eOnline: &f%size of all players%"
        wait 1 second

```
This outputs **Online:** 

whereas
```
on join:
    set title of player's scoreboard to "&6&lServer Info"
    while player is online:
        set line 1 of player's scoreboard to "&eOnline: %size of all players%"
        wait 1 second
```

Outputs, correctly, **Online: 1**

I also tried without referencing any objects, breaks when a second colour code is included

**Comment by ShaneBeee** [comment]
As show on discord I can not replicate said bug:
<img width="966" alt="Screen Shot 2020-04-01 at 1 11 58 PM" src="https://user-images.githubusercontent.com/20008482/78182175-86eef380-741a-11ea-8ace-a8bf326c9c93.png">

**Comment by Romitou** [comment]
Hi! Same here, I cannot replicate this issue in Paper 1.15.2.
![image](https://user-images.githubusercontent.com/35146758/79671475-ba779f00-81ca-11ea-954d-3ba09dd07519.png)

**Comment by ShaneBeee** [comment]
Oh right I forgot to close this.

What will failed to mention in this was that he was using a 1.8.8 client.
Due to changes in the scoreboard the issue he was having was client side. I've been told there are ways to fix it, but in my opinion it servers no purpose to play a 1.8.x client on a 1.15.2 server, therefor I'm not going to fix this.
