### ISSUE TITLE
[BUG] Empty "tag" tags are getting created on items

### ISSUE THREAD

**Issue by L3v3lup** [ShaneBeee/SkBee#331]
**Describe the bug**   
Checking an item for an NBT compound automatically creates an empty tag "tag".
In my case this made thousands of itemstacks for dozens of player unstackable and broke quite a few mechanics.

**To Reproduce**   
Example code:
```
on world change:
	loop all items in player's inventory:
		set {_nbt} to nbt compound of loop-item
		if tag "tag;CustomNBTData" of {_nbt} = "Remove":
                      stop

```
It should not do anything or change any items. After all, it still changes each item.

**Expected behavior**   
No item NBT should change.

**Version Info:**
```
SkBEE 2.7.3, Minecraft Purpur/Paper 1.19.2
```

**Additional context**   
-

**Comment by L3v3lup** [comment]
Edit:
This actually breaks all my "custom" Items -_-
I am comparing them against a saved version in a file. That means all "custom" items are different now.
This is a gigantic problem for a lot of reasons.

**Comment by ShaneBeee** [comment]
This isn't a bug, you are checking if the value of a tag = X
Because you are checking that tag, which happens to be a sub compound, the API has to create the parent compound to be able to have another tag inside of it.

Due to how the API works, this is not possible to remove. 

That said, rather than checking the value (when it doesn't exist), check if the tag is even set
https://skripthub.net/docs/?id=8033

**Comment by L3v3lup** [comment]
Okay understandable, thank you for your quick answer.
