### ISSUE TITLE
[SUGGESTION] The ability to toggle for NBT block removal

### ISSUE THREAD

**Issue by levahmc** [ShaneBeee/SkBee#348]
On our server `com.shanebeestudios.skbee.api.listener.NBTListener.onPistonPush()` is the highest on SkBee's thread usage. This makes SkBee our most intensive plugin on the main thread. We are simply looking for extra optimisation on this.

We'd like the ability to toggle NBT block removal when they are updated with pistons. 

Spark Report: https://spark.lucko.me/h8m1KmF08r

**Comment by ShaneBeee** [comment]
While I understand you are concerned about high usage of events, I'd hardly call 2.67% "high" usage, especially with a server running at 20TPS.

I also see that in Skript itself you aren't using any event listeners other than `on chat` which is a very light event.
That said, SkBee may just appear to be high, because you don't have much on your server listening to things.

At this time I don't see this event being detrimental to server performance.
If I continue to see reports regarding SkBee causing performance issues, I'll look into a way to maybe add a toggle for this.
As of right now, I don't see the need.

**Comment by ShaneBeee** [comment]
actually you know what, im going to accept this suggestion, because im going to use it for all the NBT events, ill add config options for each, in the event people don't want the nbt removed.
