### ISSUE TITLE
[SUGGESTION] Add support Dynmap syntax

### ISSUE THREAD

**Issue by pwuddle** [ShaneBeee/SkBee#419]
**Is your feature request related to a problem? Please describe.**
As stated in a previous _showcase_ post in the skUnity discord, some previous useful addons are outdated, although their features are quite nice to actually use. As an example, Sovde's new _skript-particle_ addon, which offers new, but also old _skDragon_ features. Some of these features, such as _skDynmap_'s are very useful, as seen in said showcase video, therefor the suggestion to add these features to skBee, although they might not fit within the standard skBee features.

**Describe the solution you'd like**
Addition of new features that are outdated due to their addons not being maintained. Example of such addons:
- skDynmap

**Describe alternatives you've considered**
As seen in said showcase post their goal was achieved by using the outdated addon, even though it obviously was outdated. So the actual idea was achievable, yet the execution of the idea was harder, due to there not being actual functioning syntax.

**Additional context**
> Property of Creamy Slushy / sluhtie on the skUnity discord
https://streamable.com/e60p62
https://streamable.com/d3bvng

To end my beautiful suggestion, currently there is only one additional addon whose features would be nice to have in skBee, but there are enough addons whose features also could be added, although they have not been said in this post.

**Comment by Fusezion** [comment]
Hey, for dynmap syntax, Shane had planned in the past to add support for this to bounds, however if I remember he decided to scrap it due to maintaining another api in skbee such as this would be pain, and in addition making it work was also annyoing.

Honestly, in my opinion with how large Dynmap really is it would be better off being made into it's own addon with just a hook into skbee for bound support. Adding this and their api just feels too large to actually support

**Comment by ShaneBeee** [comment]
Yeah as Fusezion state, I do not plan on adding support for anymore external APIs.
Something like this would best be done as another addon.
