### ISSUE TITLE
[SUGGESTION] Anvil combine event

### ISSUE THREAD

**Issue by not-3than** [ShaneBeee/SkBee#447]
### Suggestion

Similar to how the late TuSKe had, an event for when items in an anvil get combined. Will give the final item from the items being combined and be triggered at the same time the anvil makes the noise and closes the inventory.

The anvil prepare event, as useful as it is in a lot of scenarios, is lacking certain functionality I require for some thing I am working on.

### Alternatives

`on anvil prepare:` but it doesn't have that further functionality of the final item. I need to update the final item in an anvil combination event, but neither Paper nor SkBee had this event. TuSKe made their own event, and am asking that this is done (because I don't know how to do that)

### Additional Information

[TuSKe anvil combine event source code](https://github.com/Tuke-Nuke/TuSKe/blob/master/src/main/java/com/github/tukenuke/tuske/events/customevent/AnvilCombineEvent.java)

TuSKe itself is an outdated and bad Skript addon, yes. This doesn't mean everything in it was a bad idea.

**Comment by Fusezion** [comment]
The anvil combine event internally is just them checking an inventory click event on the result slot.
this is honestly worst than just using our PrepareAnvilEvent due to all the additional checks

The anvil prepare event is not only a native non custom event for us but also provides so much more in terms of allowing modifications.

Everything you can do in tuske's anvil combine you can do here what functionality are you saying we're missing?

**Comment by ShaneBeee** [comment]
Looking at the internal code of Tuske this is what its doing:
- inventory click event
  - do a bunch of checks
  - call that made up event

This is all stuff you can do in vanilla Skript

**Comment by Fusezion** [comment]
Closing this issue as there's been no response in 6 days and everything here is already possible is vanilla skript
