### ISSUE TITLE
[SUGGESTION] Sorting Lists

### ISSUE THREAD

**Issue by ElijahJunaid** [ShaneBeee/SkBee#511]
### Suggestion

I'd like to see the ability to sort lists with custom formats, very similar to MorkazSk's in SkBee.

### Alternatives

MorkazSk is the alternative but it'd be better to have it in SkBee where all other good features go instead of adding in another add-on for Skript that only has one purpose.

### Additional Information

https://github.com/MorkaZ/MorkazSk/blob/dd9863b87a7f8d7de79a7c4fe26e67f1f81166e7/src/main/java/com/morkaz/morkazsk/expressions/universal/ExprSortWithCustomOutput.java#L36

**Comment by ShaneBeee** [comment]
I won't be adding this to SkBee for 2 reasons:

1) Skript already has a sorted indices expression. Personally Ive never used Morkaz, but from what I've seen in the community, the one Skript provides is better/more reliable. I suggest to sticking with Skript's expression

2) SkBee's main goal is to open up the Bukkit API/Minecraft to Skripters. It's not my intention to start adding fluff syntax to make things easier on Skripters. This is the type of thing if needed, I recommend suggesting to Skript itself, since it is the base language, and sorting in my opinion is something that belongs in the base language.
