### ISSUE TITLE
[BUG] Severe Error

### ISSUE THREAD

**Issue by Coolkc456** [ShaneBeee/SkBee#556]
### What happened?

Upon adding the plugin, I receive a large error message in the console and all of my skripts stop activating until I remove SkBee.

The console contains errors related to being unable to load SkBee classes.
[latest (2).log](https://github.com/ShaneBeee/SkBee/files/13933384/latest.2.log)

### Steps to reproduce

1. Install Spigot 1.20.4
2. Add Skript 2.7.3
3. Add SkBee 3.1.0

### Expected behavior

I installed this plugin so I could paste structures and intended for it to load and not break my scripts.

### SkBee Version

3.1.0

### Server Version

Spigot 1.20.4

### SkBee Info

14.01 23:02:50 [Server] Server thread/[INFO] --- [SkBee Loading Info] ---
14.01 23:02:50 [Server] Server thread/[INFO] - [NBTAPI] Found Spigot: v1_20_R3! Trying to find NMS support
14.01 23:02:50 [Server] Server thread/[INFO] - [NBTAPI] NMS support 'MC1_20_R3' loaded!
14.01 23:02:50 [Server] Server thread/[INFO] - NBT Elements successfully loaded
14.01 23:02:50 [Server] Server thread/[INFO] - Text Component Elements successfully loaded
14.01 23:02:50 [Server] Server thread/[INFO] - Advancement Elements successfully loaded
14.01 23:02:50 [Server] Server thread/[INFO] - BossBar Elements successfully loaded
14.01 23:02:50 [Server] Server thread/[INFO] - Bound Elements successfully loaded
14.01 23:02:50 [Server] Server thread/[INFO] - Display Entity elements successfully loaded
14.01 23:02:50 [Server] Server thread/[INFO] - Fishing elements successfully loaded
14.01 23:02:50 [Server] Server thread/[INFO] - Game Event Elements successfully loaded
14.01 23:02:50 [Server] Server thread/[INFO] - Particle Elements successfully loaded
14.01 23:02:50 [Server] Server thread/[INFO] - RayTrace elements successfully loaded
14.01 23:02:50 [Server] Server thread/[INFO] - Recipe Elements successfully loaded
14.01 23:02:50 [Server] Server thread/[INFO] - Scoreboard Elements successfully loaded
14.01 23:02:50 [Server] Server thread/[INFO] - Scoreboard Objective Elements successfully loaded
14.01 23:02:50 [Server] Server thread/[INFO] - Statistic Elements successfully loaded
14.01 23:02:50 [Server] Server thread/[INFO] - Structure Elements successfully loaded
14.01 23:02:50 [Server] Server thread/[INFO] - Minecraft Tag elements successfully loaded
14.01 23:02:50 [Server] Server thread/[INFO] - Team Elements successfully loaded
14.01 23:02:50 [Server] Server thread/[INFO] - Tick Manager elements successfully loaded
14.01 23:02:50 [Server] Server thread/[INFO] - Villager Elements successfully loaded
14.01 23:02:50 [Server] Server thread/[INFO] - Virtual Furnace Elements disabled via config
14.01 23:02:50 [Server] Server thread/[INFO] - World Border Elements successfully loaded
14.01 23:02:50 [Server] Server thread/[INFO] - World Creator Elements successfully loaded
14.01 23:02:50 [Server] Server thread/[INFO] - Plugin is up to date!
14.01 23:02:50 [Server] Server thread/[INFO] --- [Server Info] ---
14.01 23:02:50 [Server] Server thread/[INFO] Server Version: 4014-Spigot-864e4ac-771182f (MC: 1.20.4)
14.01 23:02:50 [Server] Server thread/[INFO] Skript Version: 2.7.3
14.01 23:02:50 [Server] Server thread/[INFO] Skript Addons:
14.01 23:02:50 [Server] Server thread/[INFO] - skript-yaml v1.5
14.01 23:02:50 [Server] Server thread/[INFO] SkBee Version: 3.1.0
14.01 23:02:50 [Server] Server thread/[INFO] SkBee Website: https://github.com/ShaneBeee/SkBee

**Comment by Coolkc456** [comment]
For now, I have converted to Paper which resolved the issue.

**Comment by ShaneBeee** [comment]
so, I started up a spigot server to test this, and I did not have this issue.

In SkBee's code, to load text elements, it looks for a class that only Paper should have, its part of AdventureAPI.
If the class is missing (as it would be on Spigot), text elements won't load.

Looking at your error, I noticed that something on your server is adding the AdventureAPI another way, this gave it away:
`Using com.sk89q.worldedit.bukkit.adapter.impl.fawe.v1_20_R3.PaperweightFaweAdapter as the Bukkit adapter`

I downloaded FAWE, still no issues, then I downloaded Tebex... and that is when I got the error.

So yeah, it appears Tebex is adding the adventure API, therefor SkBee thinks its available, but... Tebex appears to have an outdated version of the AdventureAPI so it's missing a class.

I can't really fix issues by other plugins that are doing weird stuff like that.

Im going to mark this as "won't fix" because honestly, everyone should be using Paper at this point.
The plugin does seem to work on Spigot (not recommended), but Tebex appears to be causing issue.
