### ISSUE TITLE
Folia

### ISSUE THREAD

**Issue by Souipi** [ShaneBeee/SkBee#558]
### Suggestion

Add a folia support. That can be very usefull for network on folia.

### Alternatives

None.

**Comment by ShaneBeee** [comment]
does Skript even support folia?

**Comment by Souipi** [comment]
> does Skript even support folia?

Yea a dev version of skript support folia

**Comment by Souipi** [comment]
Here's the link of the branch : https://github.com/SkriptLang/Skript/tree/feature/folia

**Comment by ShaneBeee** [comment]
first of all, I already know about that.
Second, I asked if Skript supports it.
A branch is not a "dev" version, its just a branch where the team is starting to work on something.

That said, I have started a folia server and put Skript on it. It's nothing but a mess.
So much of it doesn't work.

I wanted to test SkBee, so I added folia support to SkBee's plugin.yml, so it will LOAD on a folia server, but many things will be broken.

So for now, I'll just say it loads, but there is no guarantee that things will work.

**Comment by Souipi** [comment]
> first of all, I already know about that. Second, I asked if Skript supports it. A branch is not a "dev" version, its just a branch where the team is starting to work on something.
> 
> That said, I have started a folia server and put Skript on it. It's nothing but a mess. So much of it doesn't work.
> 
> I wanted to test SkBee, so I added folia support to SkBee's plugin.yml, so it will LOAD on a folia server, but many things will be broken.
> 
> So for now, I'll just say it loads, but there is no guarantee that things will work.

Hummmmm nah the branch work correctly because i'm using it... If you want i can give you the jar ( dm me on discord ).
And by the way i've already try to just add folia support on the plugin.yml and i've too many errors.

**Comment by ShaneBeee** [comment]
It's literally not working correctly, Im also using it.
Things like teleport aren't working, delay effect doesn't work, lots of things don't work.
Skript isn't properly setup to truly work with Folia and It'll most likely never fully support it.

Anyways, as previously stated, I added folia support to the plugin.yml.
Some things aren't going to work, for example recipe sections throw a ton of errors, because the folia branch of Skript is missing the new API which SkBee is using (so just disable the recipe stuff in SkBee's config).

Scoreboard team stuff is also throwing errors because Folia currently does not support that API, this is out of my control.

At this time, this is the best support I can currently offer.
Since Folia is not released to the public, and is still in the development stages, as well as Skript doesn't properly support Folia, there's really nothing more I can do to support it.

Down the road when Folia is publicly released, I can maybe look at it again.

**Comment by DelayedGaming** [comment]
> I wanted to test SkBee, so I added folia support to SkBee's plugin.yml, so it will LOAD on a folia server, but many things will be broken.
It is kind of a misleading when clearly SkBee and its dependent will 99.98% break in a Folia server with `folia-supported` set to true, so I’d suggest to revert the involved commit until Skript and SkBee is functional in a Folia server at minimal.

**Comment by ShaneBeee** [comment]
> > I wanted to test SkBee, so I added folia support to SkBee's plugin.yml, so it will LOAD on a folia server, but many things will be broken.
> 
> It is kind of a misleading when clearly SkBee and its dependent will 99.98% break in a Folia server with `folia-supported` set to true, so I’d suggest to revert the involved commit until Skript and SkBee is functional in a Folia server at minimal.

yeah you’re right.
I have thought a lot about this.
While SkBee can work, and will run, it (along with Skript) is heavily broken.

I will remove that from the plugin.yml.
If anyone wants to experiment with it, they're free to add it back, and try again.

Im going to close this issue right now as there's really no need to add Folia support anytime soon for two reasons:
1) Skript itself doesn't have proper support for Folia
2) Folia itself isn't released to the public, its still in VERY EARLY development stages.
