### ISSUE TITLE
[SUGGESTION] Can break condition for items & blocks

### ISSUE THREAD

**Issue by tookender** [ShaneBeee/SkBee#563]
### Suggestion

A `can break` condition for items and blocks, so you can see for example see if the player's tool can break a block.
%itemtype% can break %block%

### Alternatives

It is possible with reflect, but it would be a neat feature in SkBee.

### Additional Information

Possible with `!Block.getDrops(ItemStack).isEmpty()`

**Comment by Fusezion** [comment]
Alright so two things
1. the code your doing yourself is already possible via Skript it's just `drops of event-block using player's tool is set`, this is not perfect due to blocks like leaves and short grass which don't have 100% chance of drops

2. Skript as of 2.7 has a condition called ["preferred tool"](https://docs.skriptlang.org/conditions.html?search=#CondIsPreferredTool) this effectively is the same thing as above except it works based off if the block will drop an item at all ever
