### ISSUE TITLE
[BUG] SkBEE wont load with FAWE

### ISSUE THREAD

**Issue by Poweringg** [ShaneBeee/SkBee#59]
**Describe the bug**
SkBEE wont load when FastAsyncWorldEdit is installed. When i remove FAWE and put in plugins WorldEdit it works.

**To Reproduce**
Add to plugins Skript 2.5, SkBEE 1.6.0 and FAWE ( https://intellectualsites.github.io/download/fawe.html or https://www.spigotmc.org/resources/fast-async-worldedit.13932/ )

**Expected behavior**
it should work together ?

**Screenshots/Errors**
![image](https://user-images.githubusercontent.com/15527318/95018311-31143600-065f-11eb-8a71-7620a06a8d1e.png)

**Version Info:**
 - **SkBee Version:** 1.6.0
-  **Skript Version:** 2.5
 - **Server Version/Platform** Paper 1.16.3 r0.1 204
- FastAsyncWorldEdit-1.16 #398

**Additional context**
...

**Comment by ShaneBeee** [comment]
Unfortunately this is not something I can replicate.

Someone else talked to me and had a similar issue. From what I could see, a plugin on their server was forcing SkBee to load before Skript. This is not something I can fix. 

I did however add FAWE as a soft depend to SkBee, and maybe that will force it to load after.
Since I can not replicate it, could you please try [**THIS BUILD**](https://github.com/ShaneBeee/SkBee/suites/1289083107/artifacts/20074520) and let me know if anything changes.

**Comment by Poweringg** [comment]
Hello, i used your build and still have same problem.

![image](https://user-images.githubusercontent.com/15527318/95187459-79506700-07cb-11eb-9138-3df1b99df36d.png)

**Comment by ShaneBeee** [comment]
Ok, Im not too sure why that is happening then. I can not replicate the issue. I installed FAWE on my server and it loaded as expected.
Im suspecting maybe another plugin is causing issue, and changing load order on your server.
The way its written, its not possible to load before Skript, so I have no clue what is going on here.

**Comment by ShaneBeee** [comment]
Closing ... not sure if this was resolved or not.
