### ISSUE TITLE
[SUGGESTION] Persistent Data Containers & Namespaced Keys

### ISSUE THREAD

**Issue by PrecedingxD** [ShaneBeee/SkBee#609]
### Suggestion

Allow for some type of syntax such as this to set Persistent Data Container (PDC)'s with NamespacedKeys:

```
        set {_key} to namespaced key with key "custom_item"

        set persistent data type string with {_key} of player's tool to "custom_item"

        if persistent data type string with {_key} of player's tool is "custom_item":
            message "You have the persistent key ""custom_item""."

        if player's tool has persistent data type string with {_key}:
            message "You have the persistent key."

        remove persistent data type string with {_key} from player's tool
```

Since PDC's allow you to create custom data types, you could implement Skript data types (such as timespans for example).
**Please keep in mind I'm not good at Skript syntax design... I was going to do this myself in a personal addon, but I have basically no knowledge of Skript's API.**

### Alternatives

Items: Checking the name of an item or lore, but that prevents customizability of items and you would have to check for everything.
Entities: Store them in a list? Doesn't seem optimal.

( Other types I haven't ever worked with enough )

### Additional Information

https://docs.papermc.io/paper/dev/pdc

**Comment by Fusezion** [comment]
So to start, we already have namespacedkeys, have had them for quite awhile actually. earliest found release version on docs is 2.6.0.
pdc, while they're interesting and a bit more flexible than nbt in select aspects (notably a wip draft paper pr adding object support) a lot of what pdcs does can be done in nbt

**Comment by ShaneBeee** [comment]
While I understand the desire to use PDC, I also detest how Bukkit created PDC.
Its awful.

That said, anything that can be done in PDC can be done using NBT.

I know you made a point about "custom types" but that would require me to essentially make a serializer for every type you'd want in PDC, and frankly, I have no desire to do that.

Personally I think something like PDC if added, should be added to Skript.
There's been attempts done several times by a few people and it just turns out messy. 

At this point I want to thank you for the suggestion but Im going to say no. 
I don't think PDC brings anything new to the table that can't already be done in SkBee.
