### ISSUE TITLE
[SUGGESTION] Client Side Glow for a player and Able to Smithing Table Recipes

### ISSUE THREAD

**Issue by KeremWho** [ShaneBeee/SkBee#73]
**Is your feature request related to a problem? Please describe.**
No, i just need this.

**Describe the solution you'd like**
1) For example i want to make a team system and I want to do glow amoung team members.
2) I added custom items to my server and i want to do upgrade netherite on smiting table.

**Describe alternatives you've considered**

**Additional context**

**Comment by ShaneBeee** [comment]
For future reference, please create a new issue per suggestion.
These 2 are widely different, and I need to track them separately

1) Ill look into the glow thing, but it might be difficult due to how Im doing scoreboards. On that note, the glow color is determined by the team a player is on. Something like this needs to be handled in a full fledged team system. If just using teams to manage colours for players, this could potentially screw up other things teams are used for (as we've already seen my scoreboards do)

2) I could add smithing recipes. The issue is Bukkit does not handle them well, and Minecraft didn't really design them all that well. When doing simple testing with smithing recipes in Java, the results were not as I would have expected.
I feel like a lot of people are going to complain about these, even though it would be out of my control how they work. But ill give it a shot.

**Comment by ShaneBeee** [comment]
I will not be adding client side glow, as this will be using packets, and SkBee doesn't handle packets
