### ISSUE TITLE
Team glowing

### ISSUE THREAD

**Issue by TheGeekGamer91** [ShaneBeee/SkBee#99]
Hello, like in the ticket #16 ,

I would like to use the color of the Minecraft teams to make entity glowing. But it's doesn't work unless if I turn off the scoreboards to false in the SkBee config.

Is it possible to do that without disable the scoreboards ? Because I use the SkBee scoreboards in some skripts.

Thanks in advance.

**Version Info:**
- Skript-2.5.3
- SkBee-1.10.0
- Paper 1.16.5

**Comment by ShaneBeee** [comment]
At this time no it is not possible.

SkBee gives each player their own scoreboard. When that happens, it disables all vanilla scoreboard functionality, since the player is no longer linked to the server's scoreboard.

in the future i may add some stuff to allow things like this to work, but thats going to be down the road, since it would require a lot of work to be done... .A LOT!

**Comment by TheGeekGamer91** [comment]
Ok, thanks you, I will find an other way.

Have a good day.
